name: Release and Publish

on: [push]

env:
  BRANCH_TAG: "${{ github.ref_name == 'main' && 'latest' || github.ref_name }}"
  BRANCH: ${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test

  publish_and_release:
    needs: build
    environment: "${{ github.ref_name == 'main' && 'prod' || '' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        if: ${{ github.ref_name == 'main'}}
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.FUNDABOT_APP_ID }}
          private_key: ${{ secrets.FUNDABOT_PRIVATE_KEY }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
  
      - uses: actions/checkout@v3
        with:
          token: ${{ github.ref_name == 'main' && steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.email "fundabot@fundwave.com"
          git config --global user.name "fundabot"

      - name: Version bump
        id: version
        uses: phips28/gh-action-bump-version@v9.1.0
        with:
          major-wording: ${{ env.BRANCH == 'main' && '[bump major]' || '[bump major --force]' }}
          minor-wording: ${{ env.BRANCH == 'main' && '[bump minor]' || '[bump minor --force]' }}
          patch-wording: ${{ null }}
          rc-wording: ${{ null }}
          default: "${{ env.BRANCH == 'main' && 'patch' || 'prerelease' }}"
          preid: "${{ env.BRANCH }}"
          skip-tag: "true"
          skip-push: "true"
          skip-commit: "true"
          bump-policy: "ignore"

      - name: Publish package
        run: npm publish --tag $BRANCH_TAG --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}

      - name: Commit changes
        env:
          VERSION: ${{ steps.version.outputs.newTag }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -a -m "CI: bumps @fundwave/fetch-queue to $VERSION"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Release
        env:
          VERSION: ${{ steps.version.outputs.newTag }}
        run: |
          if [ "${BRANCH}" != "main" ]; then PRERELEASE="-p"; fi
          echo "Releasing version ${VERSION} on branch ${BRANCH}"
          gh release create ${VERSION} --target ${BRANCH} --generate-notes ${PRERELEASE}
      
      - name: Setup .npmrc file for publish
        env:
          GITLAB_TOKEN: ${{secrets.GITLAB_TOKEN}}
        run: |
          echo @fundwave:registry=https://gitlab.com/api/v4/projects/24877554/packages/npm/ >> ~/.npmrc
          echo //gitlab.com/api/v4/projects/24877554/packages/npm/:_authToken=$GITLAB_TOKEN >> ~/.npmrc

      - name: Publish gitlab
        run:  |
          git pull origin ${{ github.ref }}
          npm ci
          npm publish --tag $BRANCH_TAG
